cropInfo = {
    ["Potato"] = {isRegrowable = false, totalGrowTime = 3},
    ["Wheat"] = {isRegrowable = false, totalGrowTime = 1},
    ["Rice"] = {isRegrowable = false, totalGrowTime = 1},
    ["Cabbage"] = {isRegrowable = false, totalGrowTime = 1},
    ["Onion"] = {isRegrowable = false, totalGrowTime = 1},
    ["Seaweed"] = {isRegrowable = false, totalGrowTime = 1},
    ["Celery"] = {isRegrowable = false, totalGrowTime = 1},
    ["Peas"] = {isRegrowable = false, totalGrowTime = 1},
    ["Chickpeas"] = {isRegrowable = false, totalGrowTime = 1},
    ["TeaLeaf"] = {isRegrowable = false, totalGrowTime = 1},
    ["SpiceLeaf"] = {isRegrowable = false, totalGrowTime = 1},
    ["Peanuts"] = {isRegrowable = false, totalGrowTime = 1},
    ["Millet"] = {isRegrowable = false, totalGrowTime = 1},
    ["Barley"] = {isRegrowable = false, totalGrowTime = 1},
    ["Cauliflower"] = {isRegrowable = false, totalGrowTime = 4},
    ["Kiwi"] = {isRegrowable = false, totalGrowTime = 2},
    ["Artichoke"] = {isRegrowable = false, totalGrowTime = 2},
    ["BrusselSprout"] = {isRegrowable = false, totalGrowTime = 2},
    ["Cassava"] = {isRegrowable = false, totalGrowTime = 2},
    ["Oats"] = {isRegrowable = false, totalGrowTime = 2},
    ["Rye"] = {isRegrowable = false, totalGrowTime = 2},
    ["SeasameSeeds"] = {isRegrowable = false, totalGrowTime = 2},
    ["SunflowerSeeds"] = {isRegrowable = false, totalGrowTime = 2},
    ["Mustard"] = {isRegrowable = false, totalGrowTime = 2},
    ["Garlic"] = {isRegrowable = false, totalGrowTime = 2},
    ["Broccoli"] = {isRegrowable = false, totalGrowTime = 4},
    ["Beet"] = {isRegrowable = false, totalGrowTime = 3},
    ["Cucumber"] = {isRegrowable = false, totalGrowTime = 3},
    ["Ginger"] = {isRegrowable = false, totalGrowTime = 3},
    ["Cotton"] = {isRegrowable = false, totalGrowTime = 3},
    ["CurryLeaf"] = {isRegrowable = false, totalGrowTime = 3},
    ["Lentil"] = {isRegrowable = false, totalGrowTime = 3},
    ["Flax"] = {isRegrowable = false, totalGrowTime = 4},
    ["Rutabaga"] = {isRegrowable = false, totalGrowTime = 4},
    ["SweetPotato"] = {isRegrowable = false, totalGrowTime = 4},
    ["Turnip"] = {isRegrowable = false, totalGrowTime = 4},
    ["Parsnip"] = {isRegrowable = false, totalGrowTime = 4},
    ["Spinach"] = {isRegrowable = false, totalGrowTime = 4},
    ["Kale"] = {isRegrowable = false, totalGrowTime = 4},
    ["Leek"] = {isRegrowable = false, totalGrowTime = 4},
    ["Quinoa"] = {isRegrowable = false, totalGrowTime = 4},
    ["Pumpkin"] = {isRegrowable = false, totalGrowTime = 5},
    ["Pineapple"] = {isRegrowable = false, totalGrowTime = 5},
    ["Bamboo"] = {isRegrowable = false, totalGrowTime = 5},
    ["Agave"] = {isRegrowable = false, totalGrowTime = 5},
    ["Watermelon"] = {isRegrowable = false, totalGrowTime = 5},
    ["SugarCane"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["GreenBeans"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["CoffeeBeans"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["SoyBeans"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["GreenGrapes"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
    ["PurpleGrapes"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["RedGrapes"] = {isRegrowable = true, totalGrowTime = 4, growthTimeAfterHarvest = 5},
    ["Asparagus"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
    ["Tomato"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Corn"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
    ["Eggplant"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Jalapeno"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
    ["Chipotle"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Habanero"] = {isRegrowable = true, totalGrowTime = 4, growthTimeAfterHarvest = 5},
    ["GreenBellPepper"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["RedBellPepper"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["YellowBellPepper"] = {isRegrowable = true, totalGrowTime = 1, growthTimeAfterHarvest = 2},
    ["Pumpkin"] = {isRegrowable = true, totalGrowTime = 4, growthTimeAfterHarvest = 5},
    ["Zucchini"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Squash"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
    ["Blueberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Strawberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Cranberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Blackberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Raspberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Elderberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["Mulberry"] = {isRegrowable = true, totalGrowTime = 3, growthTimeAfterHarvest = 4},
    ["CactusFruit"] = {isRegrowable = true, totalGrowTime = 4, growthTimeAfterHarvest = 5},
    ["Cantaloupe"] = {isRegrowable = true, totalGrowTime = 2, growthTimeAfterHarvest = 3},
}
return cropInfo
